# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import json
import time
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [8]:
csv_data = os.path.join("output_data/cities2.csv")

vacation_city = pd.read_csv(csv_data)
vacation_city

,City,Country,Date,Max Temp,Cloudiness,Humidity,Lat,Lng,Wind Speed
0,Ushuaia,AR,1592927928,33.80,90,90,-54.80,-68.30,5.23
1,Albany,US,1592928039,86.00,74,51,42.60,-73.97,9.19
2,São Filipe,CV,1592928146,81.34,6,58,14.90,-24.50,15.64
3,Qaanaaq,GL,1592928039,37.76,8,87,77.48,-69.36,0.87
4,Kalmunai,LK,1592928071,83.73,100,75,7.42,81.82,5.68
...,...,...,...,...,...,...,...,...,...
571,Grindavik,IS,1592928054,51.80,75,71,63.84,-22.43,14.99
572,Egvekinot,RU,1592928063,36.18,97,92,66.32,-179.17,1.86
573,Nago,JP,1592928194,80.60,90,94,26.59,127.98,5.82
574,Shingū,JP,1592928045,66.70,54,86,33.73,135.98,4.09
575,Srandakan,ID,1592927849,77.76,100,85,-7.94,110.25,9.71

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key = g_key)

In [19]:
locations = vacation_city[["Lat", "Lng"]]
city_humidity = vacation_city["Humidity"]


heat = gmaps.heatmap_layer(locations, weights = city_humidity, dissipating = False)
figure = gmaps.figure()
heat.max_intensity = 100
heat.point_radius = 7

# Deploy the heat layer for the figure

figure.add_layer(heat)
figure

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [20]:
clean_vacation_df = vacation_city[(vacation_city['Max Temp'] >= 75) & (vacation_city['Max Temp'] <= 90)]
clean_vacation_df = clean_vacation_df[clean_vacation_df['Wind Speed'] <= 10]
clean_vacation_df = clean_vacation_df[clean_vacation_df['Cloudiness'] <= 10]
clean_vacation_df = clean_vacation_df[clean_vacation_df['Humidity'] <= 70]
hotel_df = clean_vacation_df
hotel_df

,City,Country,Date,Max Temp,Cloudiness,Humidity,Lat,Lng,Wind Speed
10,Bastogne,BE,1592928146,79.00,0,54,50.00,5.72,1.01
13,Boa Viagem,BR,1592927946,85.06,0,49,-5.13,-39.73,8.41
31,Lappeenranta,FI,1592928029,82.99,0,27,61.06,28.19,3.36
41,Ivaiporã,BR,1592928149,76.12,0,49,-24.25,-51.68,9.53
61,Eenhana,NaN,1592928150,80.60,0,18,-17.47,16.33,8.05
69,Ocean City,US,1592928058,82.40,1,61,39.28,-74.57,8.05
113,Nola,IT,1592928154,86.00,0,34,40.92,14.53,3.00
133,Cidreira,BR,1592928065,75.18,3,59,-30.18,-50.21,6.38
137,Aljezur,PT,1592928156,80.01,2,54,37.32,-8.80,7.74
144,Gallup,US,1592928156,75.20,1,14,35.53,-108.74,3.36
181,Ofakim,IL,1592928159,82.00,0,60,31.31,34.62,3.00
182,Sierra Vista,US,1592928159,84.20,1,13,31.55,-110.30,6.93
196,Plymouth,US,1592928160,84.99,1,69,41.83,-70.83,6.93
209,Mafinga,TZ,1592928073,77.16,7,39,-7.25,35.07,5.30
233,Staines-upon-Thames,GB,1592928163,82.40,0,34,51.43,-0.51,9.17
254,Lata,PT,1592928058,87.01,0,51,40.16,-8.33,8.03
272,Corat,AZ,1592928166,86.00,0,51,40.57,49.71,6.93
287,Maunabo,PR,1592928168,90.00,5,69,18.01,-65.90,7.00
296,Placerville,US,1592928169,82.00,1,47,38.73,-120.80,3.49
311,Turbat,PK,1592928097,86.95,0,61,26.00,63.04,8.99
314,Hauterive,FR,1592928170,84.20,6,42,46.09,3.45,6.93
326,Natal,BR,1592928117,82.40,9,65,-5.79,-35.21,9.17
361,Alta Floresta,BR,1592928031,87.42,0,41,-9.88,-56.09,4.74
386,Saint George,US,1592927814,89.01,1,16,37.10,-113.58,1.63
422,Margate,GB,1592928179,79.00,0,50,51.38,1.39,3.00
438,Pimenta Bueno,BR,1592928140,89.11,0,47,-11.67,-61.19,3.74
466,Diamantino,BR,1592928183,88.63,0,30,-14.41,-56.45,7.65
478,Saurimo,AO,1592928185,84.20,0,26,-9.66,20.39,3.11
528,Millinocket,US,1592928189,82.40,1,58,45.66,-68.71,5.82
545,Ridgecrest,US,1592928191,82.40,1,28,35.62,-117.67,4.70
569,Farmington,US,1592928118,75.20,1,25,36.73,-108.22,6.93

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [21]:
hotel_df['Hotel Name'] = ""
hotel_df

,City,Country,Date,Max Temp,Cloudiness,Humidity,Lat,Lng,Wind Speed,Hotel Name
10,Bastogne,BE,1592928146,79.00,0,54,50.00,5.72,1.01,
13,Boa Viagem,BR,1592927946,85.06,0,49,-5.13,-39.73,8.41,
31,Lappeenranta,FI,1592928029,82.99,0,27,61.06,28.19,3.36,
41,Ivaiporã,BR,1592928149,76.12,0,49,-24.25,-51.68,9.53,
61,Eenhana,NaN,1592928150,80.60,0,18,-17.47,16.33,8.05,
69,Ocean City,US,1592928058,82.40,1,61,39.28,-74.57,8.05,
113,Nola,IT,1592928154,86.00,0,34,40.92,14.53,3.00,
133,Cidreira,BR,1592928065,75.18,3,59,-30.18,-50.21,6.38,
137,Aljezur,PT,1592928156,80.01,2,54,37.32,-8.80,7.74,
144,Gallup,US,1592928156,75.20,1,14,35.53,-108.74,3.36,
181,Ofakim,IL,1592928159,82.00,0,60,31.31,34.62,3.00,
182,Sierra Vista,US,1592928159,84.20,1,13,31.55,-110.30,6.93,
196,Plymouth,US,1592928160,84.99,1,69,41.83,-70.83,6.93,
209,Mafinga,TZ,1592928073,77.16,7,39,-7.25,35.07,5.30,
233,Staines-upon-Thames,GB,1592928163,82.40,0,34,51.43,-0.51,9.17,
254,Lata,PT,1592928058,87.01,0,51,40.16,-8.33,8.03,
272,Corat,AZ,1592928166,86.00,0,51,40.57,49.71,6.93,
287,Maunabo,PR,1592928168,90.00,5,69,18.01,-65.90,7.00,
296,Placerville,US,1592928169,82.00,1,47,38.73,-120.80,3.49,
311,Turbat,PK,1592928097,86.95,0,61,26.00,63.04,8.99,
314,Hauterive,FR,1592928170,84.20,6,42,46.09,3.45,6.93,
326,Natal,BR,1592928117,82.40,9,65,-5.79,-35.21,9.17,
361,Alta Floresta,BR,1592928031,87.42,0,41,-9.88,-56.09,4.74,
386,Saint George,US,1592927814,89.01,1,16,37.10,-113.58,1.63,
422,Margate,GB,1592928179,79.00,0,50,51.38,1.39,3.00,
438,Pimenta Bueno,BR,1592928140,89.11,0,47,-11.67,-61.19,3.74,
466,Diamantino,BR,1592928183,88.63,0,30,-14.41,-56.45,7.65,
478,Saurimo,AO,1592928185,84.20,0,26,-9.66,20.39,3.11,
528,Millinocket,US,1592928189,82.40,1,58,45.66,-68.71,5.82,
545,Ridgecrest,US,1592928191,82.40,1,28,35.62,-117.67,4.70,
569,Farmington,US,1592928118,75.20,1,25,36.73,-108.22,6.93,

In [22]:
for index, row in hotel_df.iterrows():
    try:
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        params = {"keyword": "hotel",
                  "radius": 5000,
                  "key": g_key}
        
        latitude = row['Lat']
        longitude = row['Lng']
        
        params["location"] = f"{latitude}, {longitude}"
        hotel_data = requests.get(base_url, params = params).json()
        hotel_df.loc[index, "Hotel Name"] = hotel_data["results"][0]["Name"]
        
    except IndexError:
        hotel_df.loc[index, "Hotel Name"] = "NaN"
        
hotel_df

,City,Country,Date,Max Temp,Cloudiness,Humidity,Lat,Lng,Wind Speed,Hotel Name
10,Bastogne,BE,1592928146,79.00,0,54,50.00,5.72,1.01,NaN
13,Boa Viagem,BR,1592927946,85.06,0,49,-5.13,-39.73,8.41,NaN
31,Lappeenranta,FI,1592928029,82.99,0,27,61.06,28.19,3.36,NaN
41,Ivaiporã,BR,1592928149,76.12,0,49,-24.25,-51.68,9.53,NaN
61,Eenhana,NaN,1592928150,80.60,0,18,-17.47,16.33,8.05,NaN
69,Ocean City,US,1592928058,82.40,1,61,39.28,-74.57,8.05,NaN
113,Nola,IT,1592928154,86.00,0,34,40.92,14.53,3.00,NaN
133,Cidreira,BR,1592928065,75.18,3,59,-30.18,-50.21,6.38,NaN
137,Aljezur,PT,1592928156,80.01,2,54,37.32,-8.80,7.74,NaN
144,Gallup,US,1592928156,75.20,1,14,35.53,-108.74,3.36,NaN
181,Ofakim,IL,1592928159,82.00,0,60,31.31,34.62,3.00,NaN
182,Sierra Vista,US,1592928159,84.20,1,13,31.55,-110.30,6.93,NaN
196,Plymouth,US,1592928160,84.99,1,69,41.83,-70.83,6.93,NaN
209,Mafinga,TZ,1592928073,77.16,7,39,-7.25,35.07,5.30,NaN
233,Staines-upon-Thames,GB,1592928163,82.40,0,34,51.43,-0.51,9.17,NaN
254,Lata,PT,1592928058,87.01,0,51,40.16,-8.33,8.03,NaN
272,Corat,AZ,1592928166,86.00,0,51,40.57,49.71,6.93,NaN
287,Maunabo,PR,1592928168,90.00,5,69,18.01,-65.90,7.00,NaN
296,Placerville,US,1592928169,82.00,1,47,38.73,-120.80,3.49,NaN
311,Turbat,PK,1592928097,86.95,0,61,26.00,63.04,8.99,NaN
314,Hauterive,FR,1592928170,84.20,6,42,46.09,3.45,6.93,NaN
326,Natal,BR,1592928117,82.40,9,65,-5.79,-35.21,9.17,NaN
361,Alta Floresta,BR,1592928031,87.42,0,41,-9.88,-56.09,4.74,NaN
386,Saint George,US,1592927814,89.01,1,16,37.10,-113.58,1.63,NaN
422,Margate,GB,1592928179,79.00,0,50,51.38,1.39,3.00,NaN
438,Pimenta Bueno,BR,1592928140,89.11,0,47,-11.67,-61.19,3.74,NaN
466,Diamantino,BR,1592928183,88.63,0,30,-14.41,-56.45,7.65,NaN
478,Saurimo,AO,1592928185,84.20,0,26,-9.66,20.39,3.11,NaN
528,Millinocket,US,1592928189,82.40,1,58,45.66,-68.71,5.82,NaN
545,Ridgecrest,US,1592928191,82.40,1,28,35.62,-117.67,4.70,NaN
569,Farmington,US,1592928118,75.20,1,25,36.73,-108.22,6.93,NaN

In [23]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [25]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
figure.add_layer(markers)


# Display figure
figure

Figure(layout=FigureLayout(height='420px'))